stages:
    - build
    - test

build:
    stage: build
    image: python:3.8-alpine
    script: 
        - echo "Building"
        - pip install --upgrade google-api-python-client google-auth-httplib2 google-auth-oauthlib
        - python3 MyEventManager.py
    coverage: '/Code coverage: \d+\.\d+/'

test:
    stage: test
    image: python:3.8-alpine
    script:
        - echo "Testing"
        - pip3 install --upgrade pip
        - python3 MyEventManagerTest.py
